ublox_dgnss:
  ros__parameters:
    #DEVICE_SERIAL_STRING: "/dev/tty_Ardusimple"
    UART1_BAUDRATE: 115200 # Tarkista Ardusimplen baudrate (usein 115200 tai 460800)
    FRAME_ID: "gps_link"
    # Mittausnopeus 10Hz (100ms välein)
    CFG_RATE_MEAS: 100 #50
    CFG_RATE_NAV: 1
    
    # Käsketään ajuria julkaisemaan standardit ROS-viestit
    publish:
      nav_sat_fix: true    # Tämä luo /fix tai /ublox_dgnss/fix topicin
      nav_pvt: true        # Julkaisee näkemäsi raakadatan ROS-viestinä
      nav_cov: true
      nav_relposned: false   # Tarvitaan vain jos käytössä kaksi GPS-antennia (Heading)
      nav_status: true
      nav_sat: true
    
    # Aktivoidaan viestit sirun sisältä USB-porttiin
    CFG_MSGOUT_UBX_NAV_PVT_USB: 1
    CFG_MSGOUT_UBX_NAV_HPPOSLLH_USB: 1
    CFG_MSGOUT_UBX_NAV_STATUS_USB: 1
    CFG_MSGOUT_UBX_NAV_SAT_USB: 1
    CFG_MSGOUT_UBX_NAV_COV_USB: 1  # AKTIVOITU: Ilman tätä EKF ei tiedä tarkkuutta!

    # Protokollat
    CFG_USBINPROT_RTCM3X: 1
    CFG_USBINPROT_UBX: 1
    CFG_USBINPROT_NMEA: 0

ntrip_client_node:
  ros__parameters:
    host: "192.168.1.31"  # MUUTA TÄHÄN: RTKBase-palvelimesi IP-osoite
    port: 2101             # Oletusportti RTK-datalla
    mountpoint: "Ukonsalmentie" # MUUTA TÄHÄN: RTKBase-mountpointtisi nimi
    authenticate: True
    username: "uknslm"       # MUUTA TÄHÄN: RTKBasen käyttäjätunnus
    password: "uknslm19"   # MUUTA TÄHÄN: RTKBasen salasana
    rtcm_frame_id: "map"
    rtcm_message_package: "rtcm_msgs"
