joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 4
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
  
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.8
    scale_angular_turbo:
      yaw: 2.0

    publish_stamped_twist: true

    enable_button: 5
    enable_turbo_button: 4

    require_enable_button: true

joy_to_arduino:
  ros__parameters:
    #action_button: 13       # Nappi, joka aktivoi kaiken
    #motor_speed_value: 40 # PWM-arvo, joka lähetetään
    mowEnable_button: 13
    mowRpmSET_value: 2200
    hoverBtnR1_button: 7
    varaReleR2_button: 6
